# Simple NN in python

This NN model is a naive implementation of a Neural Network in Python and is going to be used to train and then compare and test with a few embedded platforms. The class code is taken from [here](https://github.com/llSourcell/Make_a_neural_network/blob/master/demo.py).

## Prerequisites
You need to install jupyter notebook for this example to run. The easiest way is to install miniconda and then use conda to install nupmy and jupyter.

In [52]:
import numpy as np

In [53]:
class NeuralNetwork():
    def __init__(self, training_set_inputs, training_set_outputs, num_of_hidden_nodes):
        
        self.input = training_set_inputs
        self.y = training_set_outputs
        
        # Seed the random number generator, so it generates the same numbers
        # every time the program runs.
        np.random.seed(1)
        # Create a 3-4-1 network
        self.weights1   = np.random.rand(self.input.shape[1],num_of_hidden_nodes) 
        self.weights2   = np.random.rand(num_of_hidden_nodes,1)

    # The Sigmoid function, which describes an S shaped curve.
    # We pass the weighted sum of the inputs through this function to
    # normalise them between 0 and 1.
    def __sigmoid(self, x):
        return 1 / (1 + np.exp(-x))

    # The derivative of the Sigmoid function.
    # This is the gradient of the Sigmoid curve.
    # It indicates how confident we are about the existing weight.
    def __sigmoid_derivative(self, x):
        return x * (1 - x)

    # We train the neural network through a process of trial and error.
    # Adjusting the synaptic weights each time.
    def train(self, training_set_inputs, training_set_outputs, number_of_training_iterations):
        for iteration in range(number_of_training_iterations):
            # Pass the training set through the hidden layer
            output = self.__sigmoid(np.dot(training_set_inputs, self.weights1))
            # 2nd layer
            output2 = self.__sigmoid(np.dot(output, self.weights2))

            # Calculate the error (The difference between the desired output
            # and the predicted output).
            error = training_set_outputs - output2

            # Multiply the error by the input and again by the gradient of the Sigmoid curve.
            # This means less confident weights are adjusted more.
            # This means inputs, which are zero, do not cause changes to the weights.            
            d_weights2 = np.dot(output.T, (2*(self.y - output2) * self.__sigmoid_derivative(output2)))
            d_weights1 = np.dot(training_set_inputs.T,  (np.dot(2*(self.y - output2) * self.__sigmoid_derivative(output2), self.weights2.T) * self.__sigmoid_derivative(output)))

            # Adjust the weights.
            self.weights1 += d_weights1
            self.weights2 += d_weights2

    # The neural network predicts.
    def predict(self, inputs, debug=False):
        output = self.__sigmoid(np.dot(inputs, self.weights1))
        if debug:
            print(output)
        # 2nd layer
        return self.__sigmoid(np.dot(output, self.weights2))


## 1. Create a labeled train set with data and labels.

Now we need to create our input data and then label them. In this case `label` just means the output, so we have two labels 0 and 1, or you can just think of these labels as binary outputs, in this case. The data are those on the next table:

D2 | D1 | D0 | Label
-|-|-|-
0 | 0 | 1 | 0
1 | 1 | 1 | 1
1 | 0 | 1 | 1
0 | 1 | 1 | 0

In Python the above table is translated to those two arrays:

In [54]:
training_set_inputs = np.array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1]])
training_set_outputs = np.array([[0, 1, 1, 0]]).T

## 2. Intialise a single neuron neural network

First we need to create an `NeuralNetwork` object and initialize it. In this case initialization means that the weights will get a random value, but with using a constant seed, so the weights are re-producable per run.

In [55]:
neural_network = NeuralNetwork(training_set_inputs, training_set_outputs, 32)

#### Weights 1:

In [43]:
print(neural_network.weights1)

[[4.17022005e-01 7.20324493e-01 1.14374817e-04 3.02332573e-01
  1.46755891e-01 9.23385948e-02 1.86260211e-01 3.45560727e-01
  3.96767474e-01 5.38816734e-01 4.19194514e-01 6.85219500e-01
  2.04452250e-01 8.78117436e-01 2.73875932e-02 6.70467510e-01
  4.17304802e-01 5.58689828e-01 1.40386939e-01 1.98101489e-01
  8.00744569e-01 9.68261576e-01 3.13424178e-01 6.92322616e-01
  8.76389152e-01 8.94606664e-01 8.50442114e-02 3.90547832e-02
  1.69830420e-01 8.78142503e-01 9.83468338e-02 4.21107625e-01]
 [9.57889530e-01 5.33165285e-01 6.91877114e-01 3.15515631e-01
  6.86500928e-01 8.34625672e-01 1.82882773e-02 7.50144315e-01
  9.88861089e-01 7.48165654e-01 2.80443992e-01 7.89279328e-01
  1.03226007e-01 4.47893526e-01 9.08595503e-01 2.93614148e-01
  2.87775339e-01 1.30028572e-01 1.93669579e-02 6.78835533e-01
  2.11628116e-01 2.65546659e-01 4.91573159e-01 5.33625451e-02
  5.74117605e-01 1.46728575e-01 5.89305537e-01 6.99758360e-01
  1.02334429e-01 4.14055988e-01 6.94400158e-01 4.14179270e-01]
 [4.99

#### Weights 2:

In [44]:
print(neural_network.weights2)

[[0.90337952]
 [0.57367949]
 [0.00287033]
 [0.61714491]
 [0.3266449 ]
 [0.5270581 ]
 [0.8859421 ]
 [0.35726976]
 [0.90853515]
 [0.62336012]
 [0.01582124]
 [0.92943723]
 [0.69089692]
 [0.99732285]
 [0.17234051]
 [0.13713575]
 [0.93259546]
 [0.69681816]
 [0.06600017]
 [0.75546305]
 [0.75387619]
 [0.92302454]
 [0.71152476]
 [0.12427096]
 [0.01988013]
 [0.02621099]
 [0.02830649]
 [0.24621107]
 [0.86002795]
 [0.53883106]
 [0.55282198]
 [0.84203089]]


## 3. Train the neural network. using a training set.

Now using the above training set we can train our NN. To do that we can run it 10,000 times and make small adjustments each time.

In [49]:
neural_network.train(training_set_inputs, training_set_outputs, 10000)

print("New synaptic weights after training: \n")
print(neural_network.weights1.T)

New synaptic weights after training: 

[[ 1.59424182  0.65719524 -0.87078742]
 [ 1.08340352  0.31962716 -0.15005518]
 [-2.37247123  0.29594698  0.76194349]
 [ 0.3095739   0.1362358   0.06010926]
 [-1.22852238  0.35847517  0.68310723]
 [-0.72938725  0.59214467  0.29208906]
 [ 0.40912581 -0.18776742  0.35613284]
 [-0.07080192  0.58768645 -0.16795003]
 [ 1.43033567  0.70122635 -0.76031456]
 [ 0.48440023  0.6021348   0.3837008 ]
 [-1.00046419  0.06526647  0.34224763]
 [ 2.15398973  0.39447251 -1.03507566]
 [-0.10103213 -0.10666045  0.54098168]
 [ 2.59832631  0.0559867  -1.09502237]
 [-1.91192968  0.4700472   0.58837698]
 [-0.03869057  0.1780191   0.62805582]
 [ 0.94286902  0.04837725  0.11515252]
 [ 1.1140357  -0.07767457 -0.10010558]
 [-1.88515372 -0.20874231  0.80963432]
 [ 0.46128218  0.50101726 -0.18916382]
 [ 2.19199985 -0.03428263 -0.82915463]
 [ 1.86082832 -0.11721008 -0.39503689]
 [ 0.63634227  0.30862065 -0.14172493]
 [-0.07698548 -0.05818843  0.92128477]
 [ 0.28444551  0.54565376

## 4. Test the trained model

Now that we have a trained NN, we can test it by passing input data that it doesn't know about.


In [50]:
# All possible inputs
inputs = np.array([
    [0,0,0],
    [0,0,1],
    [0,1,0],
    [0,1,1],
    [1,0,0],
    [1,0,1],
    [1,1,0],
    [1,1,1]])

In [51]:
for i in range(0, 8):
    print("{} = {}".format(inputs[i], neural_network.predict(inputs[i])))

[0 0 0] = [0.26933375]
[0 0 1] = [0.0019808]
[0 1 0] = [0.21193171]
[0 1 1] = [0.0015728]
[1 0 0] = [0.99995267]
[1 0 1] = [0.99861344]
[1 1 0] = [0.99993064]
[1 1 1] = [0.99813219]
