# Simple NN in python

This NN model is a naive implementation of a Neural Network in Python and is going to be used to train and then compare and test with a few embedded platforms. The class code is taken from [here](https://github.com/llSourcell/Make_a_neural_network/blob/master/demo.py).

## Prerequisites
You need to install jupyter notebook for this example to run. The easiest way is to install miniconda and then use conda to install nupmy and jupyter.

In [1]:
from numpy import exp, array, random, dot

In [2]:
class NeuralNetwork():
    def __init__(self):
        # Seed the random number generator, so it generates the same numbers
        # every time the program runs.
        random.seed(1)

        # We model a single neuron, with 3 input connections and 1 output connection.
        # We assign random weights to a 3 x 1 matrix, with values in the range -1 to 1
        # and mean 0.
        self.synaptic_weights = 2 * random.random((3, 1)) - 1

    # The Sigmoid function, which describes an S shaped curve.
    # We pass the weighted sum of the inputs through this function to
    # normalise them between 0 and 1.
    def __sigmoid(self, x):
        return 1 / (1 + exp(-x))

    # The derivative of the Sigmoid function.
    # This is the gradient of the Sigmoid curve.
    # It indicates how confident we are about the existing weight.
    def __sigmoid_derivative(self, x):
        return x * (1 - x)

    # We train the neural network through a process of trial and error.
    # Adjusting the synaptic weights each time.
    def train(self, training_set_inputs, training_set_outputs, number_of_training_iterations):
        for iteration in range(number_of_training_iterations):
            # Pass the training set through our neural network (a single neuron).
            output = self.predict(training_set_inputs)

            # Calculate the error (The difference between the desired output
            # and the predicted output).
            error = training_set_outputs - output

            # Multiply the error by the input and again by the gradient of the Sigmoid curve.
            # This means less confident weights are adjusted more.
            # This means inputs, which are zero, do not cause changes to the weights.
            adjustment = dot(training_set_inputs.T, error * self.__sigmoid_derivative(output))

            # Adjust the weights.
            self.synaptic_weights += adjustment

    # The neural network predicts.
    def predict(self, inputs):
        # Pass inputs through our neural network (our single neuron).
        return self.__sigmoid(dot(inputs, self.synaptic_weights))


## 1. Intialise a single neuron neural network

First we need to create an `NeuralNetwork` object and initialize it. In this case initialization means that the weights will get a random value, but with using a constant seed, so the weights are re-producable per run.

In [3]:
neural_network = NeuralNetwork()

In [4]:
print("Random starting synaptic weights:")
print(neural_network.synaptic_weights)

Random starting synaptic weights:
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]


## 3. Create a labeled train set with data and labels.

Now we need to create our input data and then label them. In this case `label` just means the output, so we have two labels 0 and 1, or you can just think of these labels as binary outputs, in this case. The data are those on the next table:

D2 | D1 | D0 | Label
-|-|-|-
0 | 0 | 1 | 0
1 | 1 | 1 | 1
1 | 0 | 1 | 1
0 | 1 | 1 | 0

In Python the above table is translated to those two arrays:

In [5]:
training_set_inputs = array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1]])
training_set_outputs = array([[0, 1, 1, 0]]).T

## 3. Train the neural network. using a training set.

Now using the above training set we can train our NN. To do that we can run it 10,000 times and make small adjustments each time.

In [6]:
neural_network.train(training_set_inputs, training_set_outputs, 10000)

print("New synaptic weights after training: \n")
print(neural_network.synaptic_weights)

New synaptic weights after training: 

[[ 9.67299303]
 [-0.2078435 ]
 [-4.62963669]]


## 4. Test the trained model

Now that we have a trained NN, we can test it by passing input data that it doesn't know about.


In [15]:
# All possible inputs
inputs = array([
    [0,0,0],
    [0,0,1],
    [0,1,0],
    [0,1,1],
    [1,0,0],
    [1,0,1],
    [1,1,0],
    [1,1,1]])

In [17]:
for i in range(0, 8):
    print("{} = {}".format(inputs[i], neural_network.predict(inputs[i])))

[0 0 0] = [0.5]
[0 0 1] = [0.009664]
[0 1 0] = [0.44822538]
[0 1 1] = [0.00786466]
[1 0 0] = [0.99993704]
[1 0 1] = [0.99358931]
[1 1 0] = [0.9999225]
[1 1 1] = [0.99211997]
