# Simple NN in python

This NN model is a naive implementation of a Neural Network in Python and is going to be used to train and then compare and test with a few embedded platforms. The class code is taken from [here](https://github.com/llSourcell/Make_a_neural_network/blob/master/demo.py).

## Prerequisites
You need to install jupyter notebook for this example to run. The easiest way is to install miniconda and then use conda to install nupmy and jupyter.

In [14]:
import numpy as np

In [109]:
class NeuralNetwork():
    def __init__(self, training_set_inputs, training_set_outputs):
        
        self.input = training_set_inputs
        self.y = training_set_outputs
        
        # Seed the random number generator, so it generates the same numbers
        # every time the program runs.
        np.random.seed(1)
        # Create a 3-4-1 network
        self.weights1   = np.random.rand(self.input.shape[1],8) 
        self.weights2   = np.random.rand(8,1)

    # The Sigmoid function, which describes an S shaped curve.
    # We pass the weighted sum of the inputs through this function to
    # normalise them between 0 and 1.
    def __sigmoid(self, x):
        return 1 / (1 + np.exp(-x))

    # The derivative of the Sigmoid function.
    # This is the gradient of the Sigmoid curve.
    # It indicates how confident we are about the existing weight.
    def __sigmoid_derivative(self, x):
        return x * (1 - x)

    # We train the neural network through a process of trial and error.
    # Adjusting the synaptic weights each time.
    def train(self, training_set_inputs, training_set_outputs, number_of_training_iterations):
        for iteration in range(number_of_training_iterations):
            # Pass the training set through the hidden layer
            output = self.__sigmoid(np.dot(training_set_inputs, self.weights1))
            # 2nd layer
            output2 = self.__sigmoid(np.dot(output, self.weights2))

            # Calculate the error (The difference between the desired output
            # and the predicted output).
            error = training_set_outputs - output2

            # Multiply the error by the input and again by the gradient of the Sigmoid curve.
            # This means less confident weights are adjusted more.
            # This means inputs, which are zero, do not cause changes to the weights.            
            d_weights2 = np.dot(output.T, (2*(self.y - output2) * self.__sigmoid_derivative(output2)))
            d_weights1 = np.dot(training_set_inputs.T,  (np.dot(2*(self.y - output2) * self.__sigmoid_derivative(output2), self.weights2.T) * self.__sigmoid_derivative(output)))

            # Adjust the weights.
            self.weights1 += d_weights1
            self.weights2 += d_weights2

    # The neural network predicts.
    def predict(self, inputs):
        output = self.__sigmoid(np.dot(inputs, self.weights1))
        # 2nd layer
        return self.__sigmoid(np.dot(output, self.weights2))


## 1. Create a labeled train set with data and labels.

Now we need to create our input data and then label them. In this case `label` just means the output, so we have two labels 0 and 1, or you can just think of these labels as binary outputs, in this case. The data are those on the next table:

D2 | D1 | D0 | Label
-|-|-|-
0 | 0 | 1 | 0
1 | 1 | 1 | 1
1 | 0 | 1 | 1
0 | 1 | 1 | 0

In Python the above table is translated to those two arrays:

In [110]:
training_set_inputs = array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1]])
training_set_outputs = array([[0, 1, 1, 0]]).T

## 2. Intialise a single neuron neural network

First we need to create an `NeuralNetwork` object and initialize it. In this case initialization means that the weights will get a random value, but with using a constant seed, so the weights are re-producable per run.

In [111]:
neural_network = NeuralNetwork(training_set_inputs, training_set_outputs)

In [112]:
print("Random starting synaptic weights:")
print(neural_network.weights1)

Random starting synaptic weights:
[[4.17022005e-01 7.20324493e-01 1.14374817e-04 3.02332573e-01
  1.46755891e-01 9.23385948e-02 1.86260211e-01 3.45560727e-01]
 [3.96767474e-01 5.38816734e-01 4.19194514e-01 6.85219500e-01
  2.04452250e-01 8.78117436e-01 2.73875932e-02 6.70467510e-01]
 [4.17304802e-01 5.58689828e-01 1.40386939e-01 1.98101489e-01
  8.00744569e-01 9.68261576e-01 3.13424178e-01 6.92322616e-01]]


## 3. Train the neural network. using a training set.

Now using the above training set we can train our NN. To do that we can run it 10,000 times and make small adjustments each time.

In [113]:
neural_network.train(training_set_inputs, training_set_outputs, 10000)

print("New synaptic weights after training: \n")
print(neural_network.weights1)

New synaptic weights after training: 

[[ 3.22710356  3.56378795 -3.08851493 -1.87498985 -2.50247526  0.55639281
  -2.15746908  0.2717346 ]
 [-0.02255358 -0.024517    0.24141808  0.39298636 -0.07460212  0.81562393
  -0.08571442  0.65206476]
 [-1.26560218 -1.46057802  1.06139844  0.39626403  0.97518787  0.70940473
   0.72903047  0.64618586]]


## 4. Test the trained model

Now that we have a trained NN, we can test it by passing input data that it doesn't know about.


In [114]:
# All possible inputs
inputs = array([
    [0,0,0],
    [0,0,1],
    [0,1,0],
    [0,1,1],
    [1,0,0],
    [1,0,1],
    [1,1,0],
    [1,1,1]])

In [115]:
for i in range(0, 8):
    print("{} = {}".format(inputs[i], neural_network.predict(inputs[i])))

[0 0 0] = [0.22861484]
[0 0 1] = [0.00310993]
[0 1 0] = [0.18707394]
[0 1 1] = [0.00255224]
[1 0 0] = [0.99939804]
[1 0 1] = [0.99730077]
[1 1 0] = [0.99938308]
[1 1 1] = [0.99692956]
